#!/usr/bin/perl


use strict;
use warnings;
use JSON;
#use Data::Dumper;

if ( defined($ARGV[0]) and $ARGV[0] eq "config" ) {
     print "graph_title GPS Fix\n";
     print "graph_vlabel Mode\n";
     print "graph_category Sensors\n";
     print "fix.warning 3:3\n";
     print "fix.critical 2:3\n";
     print "fix.label GPS Mode\n";
} else {

my $gps = `timeout -k 10 8 gpspipe -n10 -w|grep TPV|head -n1`;

$gps=decode_json($gps);

#print Dumper($gps);

$gps=$gps->{'mode'};



	print "fix.value $gps\n";

}
