#!/usr/bin/perl


use strict;
use warnings;
use JSON;
#use Data::Dumper;

if ( defined($ARGV[0]) and $ARGV[0] eq "config" ) {
     print "graph_title GPS estimated errors\n";
     print "graph_vlabel meters\n";
     print "graph_category Sensors\n";
     print "epx.label epx\n";
     print "epy.label epy\n";
     print "epv.label epv\n";
} else {

my $gps = `timeout -k 10 8 gpspipe -n10 -w|grep TPV|head -n1`;

$gps=decode_json($gps);

#print Dumper($gps);

my $epx;
my $epy;
my $epv;


$epx=$gps->{'epx'};
$epy=$gps->{'epy'};
$epv=$gps->{'epv'};



	print "epx.value $epx\n";
	print "epy.value $epy\n";
	print "epv.value $epv\n";

}
