#!/usr/bin/perl


use strict;
use warnings;
use JSON;
#use Data::Dumper;

if ( defined($ARGV[0]) and $ARGV[0] eq "config" ) {
     print "graph_title GPS latitude\n";
     print "graph_vlabel latitude*1000\n";
     print "graph_category Sensors\n";
     print "lat.label latitude*1000\n";
} else {

my $gps = `timeout -k 10 8 gpspipe -n10 -w|grep TPV|head -n1`;

$gps=decode_json($gps);

#print Dumper($gps);

$gps=1000*$gps->{'lat'};



	print "lat.value $gps\n";

}
