#!/bin/sh
# generic plugin to display all files in a dir
#
#  Magic Markers
#  #%# family=auto
#  #%# capabilities=autoconf

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ -z "$DDIR" ] ;then
	DDIR=/sys/kernel/debug/zswap
fi

set -e

emit_config() {
	#     echo "temp.warning 65"
	#     echo "temp.critical 80"
	#     echo "temp.label CPU"
	echo "graph_title zswap stats"
	echo "graph_vlabel count"
	echo "graph_category system"
	echo "graph_args --base 1000 --logarithmic"
	#     echo "graph_scale no"

	cd $DDIR
	for f in *
	do
		flabel=$f
		f="`clean_fieldname "$f"`"
		echo "$f.label $flabel"
	done
}

emit_values() {
	cd $DDIR
	for f in * 
	do
		v="`cat $f`"
		f="`clean_fieldname "$f"`"
		echo "$f.value $v"
	done
}

case "$1" in
	autoconf)
		if [ -e $DDIR ]; then
			echo "yes"
		else
			echo "no"
		fi
			exit 0
		;;

	config)
		emit_config
		if [ "$MUNIN_CAP_DIRTYCONFIG" = "1" ]; then
			emit_values
		fi
		;;
	*)
		emit_values
		;;
esac
