#!/bin/sh
# generic plugin to display all files in a dir
#
#  Magic Markers
#  #%# family=auto
#  #%# capabilities=autoconf

#. $MUNIN_LIBDIR/plugins/plugin.sh

DDIR=/sys/kernel/debug/zswap

set -e
if [ "$1" = "autoconf" ]; then
	if [ -e $DDIR ]; then
		echo "yes"
		exit 0
	else
		echo "no"
		exit 0
	fi
elif [ "$1" = "config" ]; then
	echo "graph_title zswap stats"
	echo "graph_vlabel count"
	echo "graph_category system"
	echo "graph_args --base 1000 --logarithmic"
	#     echo "graph_scale no"

	cd $DDIR
	for f in *
	do
		v="`cat $f`"
		echo "$f.label $f"
	done

	#     echo "temp.warning 65"
	#     echo "temp.critical 80"
	#     echo "temp.label CPU"
else
	cd $DDIR
	for f in * 
	do
		v="`cat $f`"
		echo "$f.value $v"
	done
fi
